version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: chi_crud
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
